//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Index
    {
        public int DocId { get; set; }
        public int TermId { get; set; }
        public int Position { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Term Term { get; set; }
    }
}
